---
title: "Sample and Population"
description: |
  A simple introduction to sample and population. 
author:
  - name: Dr. Fadhah Alanai
date: "`r Sys.Date()`"
output: distill::distill_article
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Population 
- Population simply refers to the entire set of items, or objectives that are of interest to a specific study, such as group of people,
animals, and objectives. 

- Studying the population is not a straightforward task, challenging and impractical for many cases. One reason for that is the size of the 
population. In many real life cases, the population size is huge making it time consuming and difficult to access and collect required data
from each member of the population. 


## Sample

- Sample is a part (or a subset) of the population. 

- Sample is collected from the population under the study to make inferences about the entire population. 

- Due to sample variability, there will always be a potential for sample error. 

- Sample error refers to the difference between the population and the sample taken from it. 

## Sample techniques

- Sampling techniques can be divided into statistical and non-statistical methods. 

## Non-statistical Sampling method 

## Convenience sampling: 

1- It is a non-probability sampling technique. 
2- The researchers selected the individuals based on their availability and willingness to participate. 
3- It is easy and cost-effective in comparison to other sampling techniques. 
4- Due to the lack of random selection, it may lead to selection bias. 

## Judgment sampling:

1- It is a non-probability sampling technique. 
2- It is based on the researchers' judgment and experiences. 
3- It is cost-effective as the researchers focus on specific groups in this sampling method. 
4- This method may lead to potential bias as it is based on the researcher's judgments, and hence, the selected individuals may influenced by the researcher's bias or pre-conceptions.  


## Statistical Sampling method 

#Simple random sample: 
In simple random sampling, each person/item/subject has an equally likely chance to be selected. 

Coming Soon!



